import { Project, Tag, ToDo } from "../Store/reducer";
import { getData } from "./getData";

export const todos: ToDo[] = [
  {
    id: 1,
    order: 1,
    title: "Design wireframes",
    completed: false,
    projectId: 1,
  },
  {
    id: 2,
    order: 2,
    title: "Implement authentication",
    completed: true,
    projectId: 1,
  },
  {
    id: 3,
    order: 3,
    title: "Write unit tests",
    completed: false,
    projectId: 1,
  },
  {
    id: 4,
    order: 4,
    title: "Fix critical bugs",
    completed: true,
    projectId: 1,
  },
  {
    id: 5,
    order: 5,
    title: "Optimize performance",
    completed: false,
    projectId: 1,
  },
  {
    id: 6,
    order: 1,
    title: "Set up CI/CD pipeline",
    completed: false,
    projectId: 2,
  },
  {
    id: 7,
    order: 2,
    title: "Deploy to staging",
    completed: false,
    projectId: 2,
  },
  {
    id: 8,
    order: 3,
    title: "Conduct user testing",
    completed: true,
    projectId: 2,
  },
  {
    id: 9,
    order: 4,
    title: "Review pull requests",
    completed: false,
    projectId: 2,
  },
  {
    id: 10,
    order: 5,
    title: "Analyze metrics",
    completed: false,
    projectId: 2,
  },
  {
    id: 11,
    order: 1,
    title: "Create marketing materials",
    completed: false,
    projectId: 3,
  },
  {
    id: 12,
    order: 2,
    title: "Update documentation",
    completed: true,
    projectId: 3,
  },
  {
    id: 13,
    order: 3,
    title: "Fix critical bugs",
    completed: false,
    projectId: 3,
  },
  { id: 14, order: 4, title: "Push to GitHub", completed: false, projectId: 3 },
  {
    id: 15,
    order: 5,
    title: "Plan sprint tasks",
    completed: true,
    projectId: 3,
  },
  {
    id: 16,
    order: 6,
    title: "Conduct code review",
    completed: false,
    projectId: 3,
  },
  {
    id: 17,
    order: 1,
    title: "Refactor components",
    completed: false,
    projectId: 4,
  },
  { id: 18, order: 2, title: "Finalize UI/UX", completed: true, projectId: 4 },
  {
    id: 20,
    order: 4,
    title: "Fix critical bugs",
    completed: false,
    projectId: 4,
  },
  {
    id: 21,
    order: 5,
    title: "Write unit tests",
    completed: true,
    projectId: 4,
  },
  {
    id: 22,
    order: 6,
    title: "Configure environment variables",
    completed: false,
    projectId: 4,
  },
  {
    id: 23,
    order: 7,
    title: "Debug layout issues",
    completed: false,
    projectId: 4,
  },
  { id: 24, order: 1, title: "Push to GitHub", completed: false, projectId: 5 },
  {
    id: 25,
    order: 2,
    title: "Debug layout issues",
    completed: true,
    projectId: 5,
  },
  {
    id: 26,
    order: 3,
    title: "Check browser compatibility",
    completed: false,
    projectId: 5,
  },
  {
    id: 27,
    order: 4,
    title: "Optimize loading time",
    completed: false,
    projectId: 5,
  },
  {
    id: 28,
    order: 5,
    title: "Adjust breakpoints",
    completed: false,
    projectId: 5,
  },
  {
    id: 29,
    order: 6,
    title: "Validate user input",
    completed: true,
    projectId: 5,
  },
  {
    id: 32,
    order: 9,
    title: "Conduct code review",
    completed: true,
    projectId: 5,
  },
  {
    id: 35,
    order: 2,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 4,
  },
  { id: 36, order: 3, title: "Push to GitHub", completed: true, projectId: 4 },
  {
    id: 37,
    order: 4,
    title: "Conduct user testing",
    completed: false,
    projectId: 4,
  },
  { id: 38, order: 5, title: "Fix UI bugs", completed: true, projectId: 4 },
  {
    id: 40,
    order: 7,
    title: "Prepare release notes",
    completed: false,
    projectId: 4,
  },
  {
    id: 41,
    order: 8,
    title: "Create marketing materials",
    completed: true,
    projectId: 4,
  },
  {
    id: 42,
    order: 9,
    title: "Optimize performance",
    completed: false,
    projectId: 4,
  },
  {
    id: 44,
    order: 1,
    title: "Set up CI/CD pipeline",
    completed: true,
    projectId: 5,
  },
  {
    id: 45,
    order: 2,
    title: "Fix critical bugs",
    completed: true,
    projectId: 5,
  },
  {
    id: 46,
    order: 3,
    title: "Create test cases",
    completed: false,
    projectId: 5,
  },
  {
    id: 48,
    order: 5,
    title: "Deploy to staging",
    completed: false,
    projectId: 5,
  },
  {
    id: 49,
    order: 6,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 5,
  },
  {
    id: 50,
    order: 7,
    title: "Conduct user testing",
    completed: false,
    projectId: 5,
  },
  {
    id: 51,
    order: 8,
    title: "Write API documentation",
    completed: true,
    projectId: 5,
  },
  {
    id: 53,
    order: 10,
    title: "Prepare release notes",
    completed: false,
    projectId: 5,
  },
  {
    id: 54,
    order: 1,
    title: "Refactor components",
    completed: false,
    projectId: 6,
  },
  { id: 55, order: 2, title: "Push to GitHub", completed: false, projectId: 6 },
  {
    id: 56,
    order: 3,
    title: "Optimize performance",
    completed: false,
    projectId: 6,
  },
  {
    id: 57,
    order: 4,
    title: "Write unit tests",
    completed: false,
    projectId: 6,
  },
  { id: 58, order: 5, title: "Fix bugs", completed: false, projectId: 6 },
  {
    id: 59,
    order: 6,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 6,
  },
  { id: 60, order: 7, title: "Finalize UI/UX", completed: false, projectId: 6 },
  {
    id: 61,
    order: 8,
    title: "Prepare release notes",
    completed: true,
    projectId: 6,
  },
  {
    id: 63,
    order: 10,
    title: "Conduct user testing",
    completed: false,
    projectId: 6,
  },
  {
    id: 64,
    order: 1,
    title: "Refactor components",
    completed: true,
    projectId: 7,
  },
  { id: 65, order: 2, title: "Finalize UI/UX", completed: false, projectId: 7 },
  {
    id: 66,
    order: 3,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 7,
  },
  {
    id: 67,
    order: 4,
    title: "Prepare release notes",
    completed: false,
    projectId: 7,
  },
  { id: 68, order: 5, title: "Push to GitHub", completed: true, projectId: 7 },
  {
    id: 69,
    order: 6,
    title: "Write unit tests",
    completed: true,
    projectId: 7,
  },
  {
    id: 70,
    order: 7,
    title: "Optimize performance",
    completed: false,
    projectId: 7,
  },
  {
    id: 71,
    order: 1,
    title: "Push to GitHub",
    completed: false,
    projectId: 10,
  },
  { id: 72, order: 2, title: "Fix UI bugs", completed: true, projectId: 10 },
  {
    id: 73,
    order: 3,
    title: "Write unit tests",
    completed: false,
    projectId: 10,
  },
  {
    id: 74,
    order: 4,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 10,
  },
  {
    id: 75,
    order: 5,
    title: "Create marketing materials",
    completed: true,
    projectId: 10,
  },
  {
    id: 76,
    order: 6,
    title: "Deploy to production",
    completed: false,
    projectId: 10,
  },
  {
    id: 77,
    order: 7,
    title: "Analyze metrics",
    completed: false,
    projectId: 10,
  },
  {
    id: 78,
    order: 8,
    title: "Prepare release notes",
    completed: true,
    projectId: 10,
  },
  {
    id: 79,
    order: 9,
    title: "Conduct user testing",
    completed: false,
    projectId: 10,
  },
  {
    id: 80,
    order: 10,
    title: "Fix critical bugs",
    completed: true,
    projectId: 10,
  },
  {
    id: 81,
    order: 1,
    title: "Refactor components",
    completed: false,
    projectId: 11,
  },
  {
    id: 82,
    order: 2,
    title: "Debug layout issues",
    completed: false,
    projectId: 11,
  },
  {
    id: 83,
    order: 3,
    title: "Update documentation",
    completed: true,
    projectId: 11,
  },
  {
    id: 84,
    order: 4,
    title: "Push to GitHub",
    completed: false,
    projectId: 11,
  },
  {
    id: 85,
    order: 5,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 11,
  },
  {
    id: 86,
    order: 6,
    title: "Write API documentation",
    completed: false,
    projectId: 11,
  },
  {
    id: 87,
    order: 7,
    title: "Optimize performance",
    completed: true,
    projectId: 11,
  },
  {
    id: 88,
    order: 8,
    title: "Conduct code review",
    completed: false,
    projectId: 11,
  },
  {
    id: 89,
    order: 9,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 11,
  },
  {
    id: 90,
    order: 10,
    title: "Prepare release notes",
    completed: true,
    projectId: 11,
  },
  { id: 91, order: 1, title: "Fix bugs", completed: false, projectId: 12 },
  {
    id: 92,
    order: 2,
    title: "Push to GitHub",
    completed: false,
    projectId: 12,
  },
  {
    id: 93,
    order: 3,
    title: "Refactor components",
    completed: true,
    projectId: 12,
  },
  {
    id: 94,
    order: 4,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 12,
  },
  {
    id: 95,
    order: 5,
    title: "Conduct user testing",
    completed: true,
    projectId: 12,
  },
  {
    id: 96,
    order: 6,
    title: "Optimize performance",
    completed: false,
    projectId: 12,
  },
  {
    id: 97,
    order: 7,
    title: "Write unit tests",
    completed: true,
    projectId: 12,
  },
  {
    id: 98,
    order: 8,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 12,
  },
  {
    id: 100,
    order: 10,
    title: "Fix critical bugs",
    completed: true,
    projectId: 12,
  },
  {
    id: 101,
    order: 1,
    title: "Debug layout issues",
    completed: false,
    projectId: 13,
  },
  {
    id: 102,
    order: 2,
    title: "Optimize performance",
    completed: true,
    projectId: 13,
  },
  {
    id: 103,
    order: 3,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 13,
  },
  {
    id: 104,
    order: 4,
    title: "Write unit tests",
    completed: false,
    projectId: 13,
  },
  {
    id: 105,
    order: 5,
    title: "Create marketing materials",
    completed: false,
    projectId: 13,
  },
  {
    id: 106,
    order: 6,
    title: "Test mobile responsiveness",
    completed: true,
    projectId: 13,
  },
  {
    id: 107,
    order: 7,
    title: "Prepare release notes",
    completed: false,
    projectId: 13,
  },
  {
    id: 108,
    order: 8,
    title: "Conduct code review",
    completed: false,
    projectId: 13,
  },
  {
    id: 109,
    order: 9,
    title: "Deploy to production",
    completed: false,
    projectId: 13,
  },
  {
    id: 110,
    order: 10,
    title: "Push to GitHub",
    completed: true,
    projectId: 13,
  },
  {
    id: 111,
    order: 1,
    title: "Refactor components",
    completed: false,
    projectId: 14,
  },
  {
    id: 112,
    order: 2,
    title: "Fix critical bugs",
    completed: true,
    projectId: 14,
  },
  {
    id: 113,
    order: 3,
    title: "Create test cases",
    completed: false,
    projectId: 14,
  },
  {
    id: 114,
    order: 4,
    title: "Update documentation",
    completed: false,
    projectId: 14,
  },
  {
    id: 115,
    order: 5,
    title: "Optimize performance",
    completed: false,
    projectId: 14,
  },
  {
    id: 116,
    order: 6,
    title: "Deploy to staging",
    completed: false,
    projectId: 14,
  },
  {
    id: 117,
    order: 7,
    title: "Write unit tests",
    completed: true,
    projectId: 14,
  },
  {
    id: 118,
    order: 8,
    title: "Conduct user testing",
    completed: false,
    projectId: 14,
  },
  {
    id: 119,
    order: 9,
    title: "Push to GitHub",
    completed: false,
    projectId: 14,
  },
  {
    id: 120,
    order: 10,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 14,
  },
  {
    id: 121,
    order: 1,
    title: "Create marketing materials",
    completed: false,
    projectId: 15,
  },
  {
    id: 122,
    order: 2,
    title: "Refactor components",
    completed: false,
    projectId: 15,
  },
  { id: 123, order: 3, title: "Fix bugs", completed: true, projectId: 15 },
  {
    id: 124,
    order: 4,
    title: "Prepare release notes",
    completed: false,
    projectId: 15,
  },
  {
    id: 125,
    order: 5,
    title: "Push to GitHub",
    completed: false,
    projectId: 15,
  },
  {
    id: 126,
    order: 6,
    title: "Optimize performance",
    completed: true,
    projectId: 15,
  },
  {
    id: 127,
    order: 7,
    title: "Test mobile responsiveness",
    completed: false,
    projectId: 15,
  },
  {
    id: 128,
    order: 8,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 15,
  },
  {
    id: 129,
    order: 9,
    title: "Conduct user testing",
    completed: true,
    projectId: 15,
  },
  {
    id: 130,
    order: 10,
    title: "Write API documentation",
    completed: false,
    projectId: 15,
  },
  { id: 131, order: 1, title: "Fix UI bugs", completed: false, projectId: 16 },
  {
    id: 132,
    order: 2,
    title: "Deploy to production",
    completed: false,
    projectId: 16,
  },
  {
    id: 133,
    order: 3,
    title: "Create test cases",
    completed: false,
    projectId: 16,
  },
  {
    id: 134,
    order: 4,
    title: "Push to GitHub",
    completed: true,
    projectId: 16,
  },
  {
    id: 135,
    order: 5,
    title: "Conduct code review",
    completed: false,
    projectId: 16,
  },
  {
    id: 136,
    order: 6,
    title: "Write unit tests",
    completed: false,
    projectId: 16,
  },
  {
    id: 137,
    order: 7,
    title: "Test mobile responsiveness",
    completed: true,
    projectId: 16,
  },
  {
    id: 138,
    order: 8,
    title: "Prepare release notes",
    completed: false,
    projectId: 16,
  },
  {
    id: 139,
    order: 9,
    title: "Optimize performance",
    completed: false,
    projectId: 16,
  },
  {
    id: 140,
    order: 10,
    title: "Fix critical bugs",
    completed: false,
    projectId: 16,
  },
  { id: 142, order: 2, title: "Fix bugs", completed: false, projectId: 17 },
  {
    id: 143,
    order: 3,
    title: "Push to GitHub",
    completed: true,
    projectId: 17,
  },
  {
    id: 144,
    order: 4,
    title: "Conduct user testing",
    completed: false,
    projectId: 17,
  },
  {
    id: 145,
    order: 5,
    title: "Write API documentation",
    completed: false,
    projectId: 17,
  },
  {
    id: 146,
    order: 6,
    title: "Optimize performance",
    completed: false,
    projectId: 17,
  },
  {
    id: 147,
    order: 7,
    title: "Prepare release notes",
    completed: false,
    projectId: 17,
  },
  {
    id: 148,
    order: 8,
    title: "Finalize UI/UX",
    completed: false,
    projectId: 17,
  },
  {
    id: 161,
    order: 1,
    title: "Design revenue chart layout",
    completed: false,
    projectId: 8,
  },
  {
    id: 162,
    order: 2,
    title: "Integrate real-time data feed",
    completed: false,
    projectId: 8,
  },
  {
    id: 163,
    order: 3,
    title: "Test KPI widgets",
    completed: true,
    projectId: 8,
  },
  {
    id: 164,
    order: 4,
    title: "Add export to PDF feature",
    completed: false,
    projectId: 8,
  },
  {
    id: 165,
    order: 5,
    title: "Polish dashboard styling",
    completed: false,
    projectId: 8,
  },
  {
    id: 166,
    order: 1,
    title: "Identify outdated dependencies",
    completed: true,
    projectId: 9,
  },
  {
    id: 167,
    order: 2,
    title: "Convert class components to hooks",
    completed: false,
    projectId: 9,
  },
  {
    id: 168,
    order: 3,
    title: "Break down monolithic files",
    completed: false,
    projectId: 9,
  },
  {
    id: 169,
    order: 4,
    title: "Improve type coverage",
    completed: false,
    projectId: 9,
  },
  {
    id: 170,
    order: 5,
    title: "Add missing unit tests",
    completed: false,
    projectId: 9,
  },
  {
    id: 171,
    order: 1,
    title: "Define test variants",
    completed: false,
    projectId: 18,
  },
  {
    id: 172,
    order: 2,
    title: "Set up experiment groups",
    completed: false,
    projectId: 18,
  },
  {
    id: 173,
    order: 3,
    title: "Integrate tracking logic",
    completed: false,
    projectId: 18,
  },
  {
    id: 174,
    order: 4,
    title: "Analyze initial results",
    completed: false,
    projectId: 18,
  },
  {
    id: 175,
    order: 5,
    title: "Implement winning variant",
    completed: false,
    projectId: 18,
  },
  {
    id: 176,
    order: 1,
    title: "Recruit beta users",
    completed: true,
    projectId: 19,
  },
  {
    id: 177,
    order: 2,
    title: "Send onboarding instructions",
    completed: false,
    projectId: 19,
  },
  {
    id: 178,
    order: 3,
    title: "Collect early feedback",
    completed: false,
    projectId: 19,
  },
  {
    id: 179,
    order: 4,
    title: "Prioritize reported issues",
    completed: false,
    projectId: 19,
  },
  {
    id: 180,
    order: 5,
    title: "Reward participants",
    completed: false,
    projectId: 19,
  },
  {
    id: 181,
    order: 1,
    title: "Draft campaign messaging",
    completed: true,
    projectId: 20,
  },
  {
    id: 182,
    order: 2,
    title: "Design promotional assets",
    completed: false,
    projectId: 20,
  },
  {
    id: 183,
    order: 3,
    title: "Schedule email blasts",
    completed: false,
    projectId: 20,
  },
  {
    id: 184,
    order: 4,
    title: "Coordinate with ad partners",
    completed: false,
    projectId: 20,
  },
  {
    id: 185,
    order: 5,
    title: "Launch campaign site",
    completed: false,
    projectId: 20,
  },
];

export const projects: Project[] = [
  {
    id: 1,
    order: 1,
    title: "Redesign Marketing Website",
    completed: false,
    pinned: true,
    tags: [1, 4],
    toDos: getData("todos", 1),
  },
  {
    id: 2,
    order: 2,
    title: "Mobile App MVP Launch",
    completed: false,
    pinned: true,
    tags: [2, 3],
    toDos: getData("todos", 2),
  },
  {
    id: 3,
    order: 3,
    title: "Customer Feedback Analysis",
    completed: false,
    pinned: false,
    tags: [5],
    toDos: getData("todos", 3),
  },
  {
    id: 4,
    order: 4,
    title: "Onboarding Flow Optimization",
    completed: false,
    pinned: false,
    tags: [3, 6],
    toDos: getData("todos", 4),
  },
  {
    id: 5,
    order: 5,
    title: "Bug Fix Sprint Q2",
    completed: false,
    pinned: true,
    tags: [7, 8],
    toDos: getData("todos", 5),
  },
  {
    id: 6,
    order: 6,
    title: "Website Performance Audit",
    completed: false,
    pinned: false,

    tags: [2],
    toDos: getData("todos", 6),
  },
  {
    id: 7,
    order: 7,
    title: "Team Hiring Pipeline",
    completed: false,
    pinned: false,
    tags: [9, 10],
    toDos: getData("todos", 7),
  },
  {
    id: 8,
    order: 8,
    title: "Sales Dashboard Metrics",
    completed: false,
    pinned: false,
    tags: [4],
    toDos: getData("todos", 8),
  },
  {
    id: 9,
    order: 9,
    title: "Refactor Legacy Codebase",
    completed: false,
    pinned: false,

    tags: [1],
    toDos: getData("todos", 9),
  },
  {
    id: 10,
    order: 10,
    title: "Q3 Content Strategy Plan",
    completed: false,
    pinned: false,
    tags: [3, 6],
    toDos: getData("todos", 10),
  },
  {
    id: 11,
    order: 11,
    title: "Push Notifications Setup",
    completed: false,
    pinned: false,
    tags: [7],
    toDos: getData("todos", 11),
  },
  {
    id: 12,
    order: 12,
    title: "Analytics Integration v2",
    completed: false,
    pinned: true,
    tags: [4, 8],
    toDos: getData("todos", 12),
  },
  {
    id: 13,
    order: 13,
    title: "Customer Support Chatbot",
    completed: false,
    pinned: false,
    tags: [6, 10],
    toDos: getData("todos", 13),
  },
  {
    id: 14,
    order: 14,
    title: "Company Blog Redesign",
    completed: false,
    pinned: false,
    tags: [3],
    toDos: getData("todos", 14),
  },
  {
    id: 15,
    order: 15,
    title: "DevOps Automation Setup",
    completed: false,
    pinned: false,
    tags: [2, 7],
    toDos: getData("todos", 15),
  },
  {
    id: 16,
    order: 16,
    title: "Internationalization Rollout",
    completed: false,
    pinned: false,
    tags: [5, 9],
    toDos: getData("todos", 16),
  },
  {
    id: 17,
    order: 17,
    title: "Security Audit & Compliance",
    completed: false,
    pinned: false,
    tags: [1, 8],
    toDos: getData("todos", 17),
  },
  {
    id: 18,
    order: 18,
    title: "New Feature A/B Testing",
    completed: false,
    pinned: false,
    tags: [4, 6],
    toDos: getData("todos", 18),
  },
  {
    id: 19,
    order: 19,
    title: "Beta User Program",
    completed: false,
    pinned: false,
    tags: [3, 5, 9, 8, 7],
    toDos: getData("todos", 19),
  },
  {
    id: 20,
    order: 20,
    title: "Holiday Campaign Launch",
    completed: false,
    pinned: true,
    tags: [4, 10],
    toDos: getData("todos", 20),
  },
];

export const tags: Tag[] = [
  { id: 1, title: "Marketing" },
  { id: 2, title: "Mobile App" },
  { id: 3, title: "Customer Feedback" },
  { id: 4, title: "Dashboard" },
  { id: 5, title: "Analysis" },
  { id: 6, title: "Optimization" },
  { id: 7, title: "Bug Fixes" },
  { id: 8, title: "Performance" },
  { id: 9, title: "Hiring" },
  { id: 10, title: "Content Strategy" },
];
